Doc + fixes
Project-ODE/OSmOSE_package pull request #19
Opened 2023-03-29 13:45 UTC by Rumengol

Completed docstring and light fixes

2023-03-31 09:25 UTC, cazaudo requested changes
just very small spelling errors

plus this PR makes me think that it would be very useful to have a document summarizing the "rules" chosen concerning permissions , translated into english sentences because the team is not very familiar with permission codes , eg 'Any member of gosmose has the right to read spectrograms from another gosmose member' , "Raw audio data cannot be deleted by anyone but the proprietary" , true for spectrogram data too ? what happens in case someone wants to create a spectrogram set already created by somebody else ? anyone can add raw auxiliary data ?

2023-03-31 09:25 UTC, cazaudo commented on src/OSmOSE/Dataset.py
> +        -------
correction of a few spelling errors : 

        This function does in order:
        - If there is any audio file in the top directory, consider them all original and create the data/audio/original/ directory before
            moving all audio files in ???
        - If there is only one folder in the top directory, move it to /data/audio/original.
        - If there is a folder named "original" in the raw audio path, then return it
        - If there is only one folder in the raw audio path, then return it as the original.
        If none of the above is true, then a ValueError is raised as the original folder could not be found nor created.

2023-03-31 09:25 UTC, cazaudo commented on src/OSmOSE/cluster/resample.py
> +    """Resample all audio files in a directory to a target sample rate and write them to a new directory.
"""Resample all audio files from a given directory to a target sample rate and write them to a new directory.

2023-03-31 09:26 UTC, cazaudo commented
perhaps my comment should be converted into an issue , let me know

2023-04-03 08:25 UTC, Rumengol commented
It's a good idea, I will add a section in the wiki explaining the permission choices.
Currently, everyone in the osmose group has all permissions over all files in the dataset, even the raw audio data, and the others can only read. We could discuss the need for more precise permissions.

If someone tries to create an already generated spectrogram set, it will regenerate it today, but we should prevent the waste of resource by checking for spectrogram existence first, I will create an issue addressing it.

2023-04-05 13:00 UTC, merged